/* nc_flexio_host.c — FlexIO host-side setup for DPA blocks.
 *
 * Loads the DPA program (nc_dpa_app — a struct flexio_app* created by DPACC),
 * creates a FlexIO process, sets up CQ/RQ/SQ queues, and activates the
 * DPA event handler (nc_dpa_event_handler, stub generated by DPACC).
 *
 * Build note: this file must be compiled together with the DPACC-generated
 * stub file (dpa_dev_entry.c compiled with `dpacc`) so that nc_dpa_app and
 * nc_dpa_event_handler are resolved at link time.
 */
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

#include <infiniband/verbs.h>
#include <libflexio/flexio.h>

#include <doca_log.h>
#include "nc_runtime.h"

DOCA_LOG_REGISTER(NC_FLEXIO_HOST);

#define NC_DPA_LOG_Q_DEPTH  7           /* 128 entries */
#define NC_DPA_Q_DATA_SZ    (128 * 2048)

/* DPACC-generated symbols — resolved when the .dpa binary is linked in */
extern struct flexio_app  *nc_dpa_app;        /* DPA application object  */
extern flexio_func_t       nc_dpa_event_handler; /* DPA event handler stub */

struct nc_flexio_ctx {
    struct ibv_context      *ibv_ctx;
    struct flexio_process   *process;
    struct ibv_pd           *pd;
    struct flexio_uar       *uar;   /* obtained from process, not created */

    struct flexio_cq        *rq_cq;
    struct flexio_rq        *rq;

    struct flexio_cq        *sq_cq;
    struct flexio_sq        *sq;

    struct flexio_mkey      *rq_mkey;
    struct flexio_mkey      *sq_mkey;

    struct flexio_event_handler *event_handler;
    flexio_uintptr_t             app_data_daddr;
};

static struct nc_flexio_ctx g_flexio;

/* Open IBV device by name (e.g. "mlx5_0") */
static int nc_flexio_open_device(const char *dev_name)
{
    struct ibv_device **devs = ibv_get_device_list(NULL);
    if (!devs) return -1;
    for (int i = 0; devs[i]; i++) {
        if (!strcmp(ibv_get_device_name(devs[i]), dev_name)) {
            g_flexio.ibv_ctx = ibv_open_device(devs[i]);
            ibv_free_device_list(devs);
            return g_flexio.ibv_ctx ? 0 : -1;
        }
    }
    ibv_free_device_list(devs);
    DOCA_LOG_ERR("IBV device '%s' not found", dev_name);
    return -1;
}

/*
 * nc_flexio_init — open device, create FlexIO process, set up queues.
 * Returns the FlexIO RQ (so the TIR can be obtained for flow steering),
 * or NULL on failure.
 */
struct flexio_rq *nc_flexio_init(const char *dev_name)
{
    /* 1. Open IBV device */
    if (nc_flexio_open_device(dev_name) != 0) {
        DOCA_LOG_ERR("Failed to open IBV device '%s'", dev_name);
        return NULL;
    }

    /* 2. Create FlexIO process (loads nc_dpa_app onto DPA) */
    if (flexio_process_create(g_flexio.ibv_ctx, nc_dpa_app, NULL,
                               &g_flexio.process) != 0) {
        DOCA_LOG_ERR("Failed to create FlexIO process");
        return NULL;
    }

    /* 3. Get PD and UAR from the process (no need to alloc separately) */
    g_flexio.pd  = flexio_process_get_pd(g_flexio.process);
    g_flexio.uar = flexio_process_get_uar(g_flexio.process);

    /* 4. Create event handler first (RQ CQ needs its thread) */
    struct flexio_event_handler_attr eh_attr = {0};
    eh_attr.host_stub_func = nc_dpa_event_handler;
    eh_attr.affinity.type  = FLEXIO_AFFINITY_NONE;
    if (flexio_event_handler_create(g_flexio.process, &eh_attr,
                                     &g_flexio.event_handler) != 0) {
        DOCA_LOG_ERR("Failed to create FlexIO event handler");
        return NULL;
    }

    /* 5. Create RQ CQ (DPA thread triggered) */
    struct flexio_cq_attr rqcq_attr = {0};
    rqcq_attr.log_cq_depth  = NC_DPA_LOG_Q_DEPTH;
    rqcq_attr.element_type  = FLEXIO_CQ_ELEMENT_TYPE_DPA_THREAD;
    rqcq_attr.thread        =
        flexio_event_handler_get_thread(g_flexio.event_handler);
    if (flexio_cq_create(g_flexio.process, NULL, &rqcq_attr,
                          &g_flexio.rq_cq) != 0) {
        DOCA_LOG_ERR("Failed to create FlexIO RQ CQ");
        return NULL;
    }
    uint32_t rq_cq_num = flexio_cq_get_cq_num(g_flexio.rq_cq);

    /* 6. Create SQ CQ (non-DPA, host-side completions) */
    struct flexio_cq_attr sqcq_attr = {0};
    sqcq_attr.log_cq_depth = NC_DPA_LOG_Q_DEPTH;
    sqcq_attr.element_type = FLEXIO_CQ_ELEMENT_TYPE_NON_DPA_CQ;
    if (flexio_cq_create(g_flexio.process, NULL, &sqcq_attr,
                          &g_flexio.sq_cq) != 0) {
        DOCA_LOG_ERR("Failed to create FlexIO SQ CQ");
        return NULL;
    }
    uint32_t sq_cq_num = flexio_cq_get_cq_num(g_flexio.sq_cq);

    /* 7. Allocate RQ data buffer on DPA heap */
    flexio_uintptr_t rq_data_daddr = 0;
    if (flexio_buf_dev_alloc(g_flexio.process, NC_DPA_Q_DATA_SZ,
                              &rq_data_daddr) != 0) {
        DOCA_LOG_ERR("Failed to alloc RQ data buffer on DPA heap");
        return NULL;
    }
    struct flexio_mkey_attr mkey_attr = {0};
    mkey_attr.pd     = g_flexio.pd;
    mkey_attr.daddr  = rq_data_daddr;
    mkey_attr.len    = NC_DPA_Q_DATA_SZ;
    mkey_attr.access = IBV_ACCESS_LOCAL_WRITE;
    if (flexio_device_mkey_create(g_flexio.process, &mkey_attr,
                                   &g_flexio.rq_mkey) != 0) {
        DOCA_LOG_ERR("Failed to create RQ mkey");
        return NULL;
    }

    /* 8. Create RQ — third arg is the CQ number (not a pointer) */
    struct flexio_wq_attr rq_attr = {0};
    rq_attr.log_wq_depth = NC_DPA_LOG_Q_DEPTH;
    rq_attr.pd           = g_flexio.pd;
    if (flexio_rq_create(g_flexio.process, NULL, rq_cq_num,
                          &rq_attr, &g_flexio.rq) != 0) {
        DOCA_LOG_ERR("Failed to create FlexIO RQ");
        return NULL;
    }

    /* 9. Allocate SQ data buffer and create SQ */
    flexio_uintptr_t sq_data_daddr = 0;
    if (flexio_buf_dev_alloc(g_flexio.process, NC_DPA_Q_DATA_SZ,
                              &sq_data_daddr) != 0) {
        DOCA_LOG_ERR("Failed to alloc SQ data buffer on DPA heap");
        return NULL;
    }
    mkey_attr.daddr = sq_data_daddr;
    if (flexio_device_mkey_create(g_flexio.process, &mkey_attr,
                                   &g_flexio.sq_mkey) != 0) {
        DOCA_LOG_ERR("Failed to create SQ mkey");
        return NULL;
    }

    struct flexio_wq_attr sq_attr = {0};
    sq_attr.log_wq_depth = NC_DPA_LOG_Q_DEPTH;
    sq_attr.pd           = g_flexio.pd;
    if (flexio_sq_create(g_flexio.process, NULL, sq_cq_num,
                          &sq_attr, &g_flexio.sq) != 0) {
        DOCA_LOG_ERR("Failed to create FlexIO SQ");
        return NULL;
    }

    DOCA_LOG_INFO("FlexIO init: RQ wq_num=%u SQ wq_num=%u",
                  flexio_rq_get_wq_num(g_flexio.rq),
                  flexio_sq_get_wq_num(g_flexio.sq));
    return g_flexio.rq;
}

/*
 * nc_flexio_start — copy queue info to DPA heap and activate event handler.
 * The transfer struct layout must match nc_dpa_app_data_t in dpa_dev_entry.c.
 */
int nc_flexio_start(void)
{
    struct {
        uint32_t rq_cq_num;
        uint32_t rq_num;
        uint32_t sq_cq_num;
        uint32_t sq_num;
        uint32_t rq_mkey_id;
        uint32_t sq_mkey_id;
    } app_data = {
        .rq_cq_num  = flexio_cq_get_cq_num(g_flexio.rq_cq),
        .rq_num     = flexio_rq_get_wq_num(g_flexio.rq),
        .sq_cq_num  = flexio_cq_get_cq_num(g_flexio.sq_cq),
        .sq_num     = flexio_sq_get_wq_num(g_flexio.sq),
        .rq_mkey_id = flexio_mkey_get_id(g_flexio.rq_mkey),
        .sq_mkey_id = flexio_mkey_get_id(g_flexio.sq_mkey),
    };

    if (flexio_copy_from_host(g_flexio.process, &app_data, sizeof(app_data),
                               &g_flexio.app_data_daddr) != 0) {
        DOCA_LOG_ERR("Failed to copy app_data to DPA heap");
        return -1;
    }

    if (flexio_event_handler_run(g_flexio.event_handler,
                                  g_flexio.app_data_daddr) != 0) {
        DOCA_LOG_ERR("Failed to run FlexIO event handler");
        return -1;
    }

    DOCA_LOG_INFO("DPA event handler activated");
    return 0;
}

void nc_flexio_destroy(void)
{
    if (g_flexio.event_handler)
        flexio_event_handler_destroy(g_flexio.event_handler);
    if (g_flexio.rq)       flexio_rq_destroy(g_flexio.rq);
    if (g_flexio.sq)       flexio_sq_destroy(g_flexio.sq);
    if (g_flexio.rq_cq)    flexio_cq_destroy(g_flexio.rq_cq);
    if (g_flexio.sq_cq)    flexio_cq_destroy(g_flexio.sq_cq);
    if (g_flexio.rq_mkey)  flexio_device_mkey_destroy(g_flexio.rq_mkey);
    if (g_flexio.sq_mkey)  flexio_device_mkey_destroy(g_flexio.sq_mkey);
    if (g_flexio.process)  flexio_process_destroy(g_flexio.process);
    if (g_flexio.ibv_ctx)  ibv_close_device(g_flexio.ibv_ctx);
}

struct flexio_rq *nc_flexio_get_rq(void) { return g_flexio.rq; }
