//===- BF3DRMT.td - BF3 NIC ASIC DRMT dialect master include *- tablegen -*-===//
//===----------------------------------------------------------------------===//

#ifndef BF3DRMT_DIALECT_BF3DRMT_BF3DRMT_TD
#define BF3DRMT_DIALECT_BF3DRMT_BF3DRMT_TD

include "Dialect/Backend/BF3/DRMT/IR/BF3DRMTDialect.td"
include "Dialect/Backend/BF3/DRMT/IR/BF3DRMTOps.td"
include "Dialect/Backend/BF3/DRMT/IR/BF3DRMTTypes.td"

#endif // BF3DRMT_DIALECT_BF3DRMT_BF3DRMT_TD
