//===- BF2DRMT.td - BF3 NIC ASIC DRMT dialect master include *- tablegen -*-===//
//===----------------------------------------------------------------------===//

#ifndef BF2DRMT_DIALECT_BF2DRMT_BF2DRMT_TD
#define BF2DRMT_DIALECT_BF2DRMT_BF2DRMT_TD

include "Dialect/Backend/BF2/DRMT/IR/BF2DRMTDialect.td"
include "Dialect/Backend/BF2/DRMT/IR/BF2DRMTOps.td"
include "Dialect/Backend/BF2/DRMT/IR/BF2DRMTTypes.td"

#endif // BF2DRMT_DIALECT_BF2DRMT_BF2DRMT_TD
